config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :loos
  resources :notes
  resources :review_notes
  resources :reviews
  resources :trips
  resources :users
  resources :charities

  root 'loos#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/charity.rb
class Charity < ApplicationRecord
end

app/models/loo.rb
class Loo < ApplicationRecord

  has_many :reviews

end

app/models/note.rb
class Note < ApplicationRecord

  has_many :review_notes
  has_many :reviews, through: :review_notes
  
end

app/models/review.rb
class Review < ApplicationRecord

  belongs_to :loo
  belongs_to :user
  belongs_to :trip

  has_many :review_notes
  has_many :notes, through: :review_notes

  after_create do
    self.loo.stars = self.loo.reviews.sum(:stars) / self.loo.reviews.count
    self.loo.save
  end
  
end

app/models/review_note.rb
class ReviewNote < ApplicationRecord

  belongs_to :review
  belongs_to :note

end

app/models/trip.rb
class Trip < ApplicationRecord

  belongs_to :user
  belongs_to :loo
  
  has_one :review

end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/charities_controller.rb
class CharitiesController < ApplicationController

  def index
    @charities = Charity.all
  end

end

app/controllers/loos_controller.rb
class LoosController < ApplicationController

  def index
    @loos = Loo.all
  end

  def show
    @loo = Loo.find(params[:id])
  end

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def show
    @review = Review.find(params[:id])
  end

  def new
    @review = Review.new
    @loo = Loo.find(params[:loo_id])
  end

  def create
    # Save the trip first
    review_params[:trip][:started_at] = DateTime.parse(review_params[:trip][:started_at])
    review_params[:trip][:ended_at] = DateTime.parse(review_params[:trip][:ended_at])
    @trip = Trip.new(review_params[:trip])
    @trip.save

    # Save the review, it's OK if trip failed (for now)
    @review = Review.new(review_params[:review])
    @review.trip = @trip

    if @review.save
      # Save review notes
      review_params[:notes].each do |i, v|
        @review.review_notes.create(note_id: i) if v == '1'
      end
      redirect_to @review
    else
      # TODO: SOMETHING BETTER
      # render 'new'
      redirect_to new_trip_path(loo_id: review_params[:trip][:loo_id])
    end
  end

  private

    def review_params
      params.require(:trip).permit!
      params.require(:review).permit!
      params.require(:notes).permit!
      params
    end

end

app/controllers/trips_controller.rb
class TripsController < ApplicationController

  def new
    @trip = Trip.new
    @loo = Loo.find(params[:loo_id])
    @user = User.order('RANDOM()').first
    @notes = Note.all
    @review = Review.new(user: @user, loo: @loo)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charities_helper.rb
module CharitiesHelper
end

app/helpers/loos_helper.rb
module LoosHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/review_notes_helper.rb
module ReviewNotesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/reviews/_short.html.erb
<b><%= link_to review.user.name, review.user %></b> poo'd here <i><%= review.created_at.to_s(:long) %></i><br>
<%= render 'reviews/stars', review: review %><br>
<% review.notes.each do |note| %>
  <span class="badge"><%= note.name %></span>
<% end %>
<p><%= review.comments %></p>

app/views/reviews/_stars.html.erb
<% (1..review.stars).each do %>
  <span class="glyphicon glyphicon-star"></span>
<% end %>

app/views/reviews/show.html.erb
<h1>Thank you for your review!</h1>

<h4><%= link_to @review.loo.name, @review.loo %></h4>
<div>
  <%= render 'reviews/short', review: @review %>
</div>

<% unless @review.trip.nil? %>
<div class="panel panel-warning" id="give-shit">
  <div class="panel-body">
    You made <span class="earnings"><%= number_to_currency(@review.trip.earnings) %></span> on the toilet!<br>
    You could have spent that on:
    <i>1,000 Loo Review buttons!</i><br>
    <b>OR <small>(better yet)</small></b><br>
    <a href="<%= charities_path %>" class="btn btn-success btn-block">Give a $hit!</a>
  </div>
</div>
<% end %>